-- DO NOT RUN. THIS SCRIPT IS FOR REFERENCE ONLY.
CREATE WAREHOUSE IF NOT EXISTS Group4_Asg2
WITH 
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS Group4_Asg2;

USE DATABASE Group4_Asg2;

CREATE SCHEMA IF NOT EXISTS raw_data;
CREATE SCHEMA IF NOT EXISTS cleaned_data; -- Cleaned data no feature engineering
CREATE SCHEMA IF NOT EXISTS final_data; -- With features
