USE WAREHOUSE GROUP4_ASG2;
USE DATABASE Group4_Asg2;

-- HDB_Price_Range - Lv
CREATE OR REPLACE TABLE FINAL_DATA.HDB_Price_Range AS
SELECT * FROM CLEANED_DATA.HDB_Price_Range;

-- HDB Property Info - Lv
CREATE OR REPLACE TABLE FINAL_DATA.HDB_Property_Info AS
SELECT * FROM CLEANED_DATA.HDB_Property_Info;

ALTER TABLE CLEANED_DATA.HDB_Property_Info
ADD COLUMN REMAINING_LEASE NUMBER(3,0) 
AS (99 - (EXTRACT(YEAR FROM CURRENT_DATE()) - YEAR_COMPLETED));

-- HDB Resale Index - Lv
CREATE OR REPLACE TABLE FINAL_DATA.HDB_Resale_Index AS
SELECT * FROM CLEANED_DATA.HDB_Resale_Index;

-- HDB Median Resale Price - Lv
CREATE OR REPLACE TABLE FINAL_DATA.HDB_Median_Resale_Price AS
SELECT * FROM CLEANED_DATA.HDB_Median_Resale_Price;
