CREATE OR REPLACE TABLE RAW_DATA.RETAIL_PHARMACY (
    location VARIANT
);

COPY INTO RAW_DATA.RETAIL_PHARMACY
FROM @stage/"Retail pharmacy locations (GEOJSON).geojson"
FILE_FORMAT = (TYPE = JSON)
ON_ERROR = 'CONTINUE';
