CREATE OR REPLACE TABLE RAW_DATA.WATER_ACTIVITIES (
    location VARIANT
);

COPY INTO RAW_DATA.WATER_ACTIVITIES
FROM @stage/WaterActivities@SG.geojson
FILE_FORMAT = (TYPE = JSON)
ON_ERROR = 'CONTINUE';
