CREATE OR REPLACE TABLE RAW_DATA.ELDERCARE_SERVICES (
    location VARIANT
);

COPY INTO RAW_DATA.ELDERCARE_SERVICES
FROM @stage/EldercareServices.geojson
FILE_FORMAT = (TYPE = JSON)
ON_ERROR = 'CONTINUE';
