CREATE OR REPLACE TABLE RAW_DATA.HAWKER_CENTRES (
    location VARIANT
);

COPY INTO RAW_DATA.HAWKER_CENTRES
FROM @stage/HawkerCentresGEOJSON.geojson
FILE_FORMAT = (TYPE = JSON)
ON_ERROR = 'CONTINUE';
